### ISSUE TITLE
AxTilemap.scale?

### ISSUE THREAD

**Issue by Wiering** [arkeus/Axel#1]
Changing AxTilemap.scale doesn't seem to do anything, for example in the AxeliteBasic demo I'm trying:

```
        ...
        tilemap.scale.x = 4;
        tilemap.scale.y = 4;
        add (tilemap);
```

**Comment by arkeus** [comment]
Oh yes, currently tilemaps don't implement everything that drawables have
(I don't think rotating them works either, for example). They might be
something I will support, but it requires a bit extra (for example, to make
collision work on a scaled tilemap). Typically, I don't see scaling
tilemaps as a very common occurrence though, so it's lower on the priority
list.

On Thu, Apr 19, 2012 at 6:50 PM, Wiering <
reply@reply.github.com

**Comment by Wiering** [comment]
I generally use it to have multiple background layers that use the same graphics but each one at a smaller size (and different shade).

**Comment by arkeus** [comment]
I'll look into supporting scale for tilemaps. However, unlike flixel where tilemaps are a single bitmap, here each tile is a separate quad, so scaling can get tricky (with zooming at non-integer scales, I had some issues). If I can support it, I'll get it in there. :)
